apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orc-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orc-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: orc-controller-manager
  namespace: orc-system
