apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orc-manager-role
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
