apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: orc
  name: orc-leader-election-rolebinding
  namespace: orc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orc-leader-election-role
subjects:
- kind: ServiceAccount
  name: orc-controller-manager
  namespace: orc-system
