name: Pull Request
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
env:
  GO_VERSION: 1.22.5
jobs:
  helm-template:
    name: 'Test Helm Template'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Make Charts
      run: make
    - name: Generate Documentation
      run: make docs
    - name: Generated Code Checked In
      run: '[[ -z $(git status --porcelain) ]]'
    - name: Run Test
      run: make test
